nameservers:
  shiro-ns:
    ip: 136.116.159.118
  osaka-ns:
    ip: 34.55.170.241

agent_secret: dEcartes2026
domain: dnsproof.org
primary_ns: "shiro-ns"

enable_password_protect: true
password: shiro123

tls_enabled: false
agent_cert_path_ns: "/etc/ssl/dnsproof"
agent_cert_path_app: "../agent.crt"