nameservers:
  ns1:
    ip: 136.116.159.118
  ns2:
    ip: 34.55.170.241

agent_secret: my-hmac-agent-secret
domain: dnsproof.org
primary_ns: ns1

enable_password_protect: true
password: my-secret-app-password

tls_enabled: false
agent_cert_path_ns: "/etc/ssl/dnsproof"
agent_cert_path_app: "../agent.crt"