nameservers:
  ns1:
    ip: 136.119.120.167
  ns2:
    ip: 34.171.85.147

domain: dnsproof.org
primary_ns: "ns1"

resolver: nsd # coredns or nsd

tls_enabled: true
agent_cert_path_ns: "/etc/ssl/dnsproof"
agent_cert_path_app: "../tls_cert"